# Generated by Django 6.0.5 on 2026-08-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_latitude_user_longitude_user_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleradditionaldetails',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selleradditionaldetails',
            name='business_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selleradditionaldetails',
            name='business_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
