# Generated by Django 6.0.6 on 2026-08-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleradditionaldetails_business_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=10)),
                ('free_radius_km', models.FloatField(default=2)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('peak_hour_pct', models.FloatField(default=0)),
                ('weekend_pct', models.FloatField(default=0)),
                ('emergency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to='accounts.service')),
            ],
            options={
                'db_table': 'service_locations',
            },
        ),
    ]
